[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
mlua = { version = "0.10.2", features = ["luau-jit", "vendored"] }
package = { path = "../package" }
raylib-ffi = "5.5.0"
# raylib-sys = "5.0.2"
