[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
gl = "0.14.0"
gltf = "1.4.1"
mlua = { version = "0.10.2", features = ["luau-jit", "vendored"] }
package = { path = "../package" }
sdl2 = { version = "0.37.0", features = ["bundled"] }
