[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
package = { path = "../package" }
raylib-sys = "5.0.2"
rquickjs = { version = "0.6.2", features = ["macro"] }
