[profile.release]
strip = true
lto = true
panic = "abort"

[profile.dev]
strip = true

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["client", "common", "package", "server"]
